apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: otel-legacy-route
  namespace: monitoring
spec:
  parentRefs:
    - name: observability-gateway
      sectionName: otel-legacy
  rules:
    - backendRefs:
        - name: otel-collector
          port: 4317
